### ISSUE TITLE
I cant make pynotifier to work on Python 3 in Linux

### ISSUE THREAD

**Issue by jgardounis** [YuriyLisovskiy/pynotifier#3]
I applied the code on the readme a Python /Django webapp  on a Linux server, in such a way so that it runs after the completion of an action.  But while the action runs normally, I do not see any notification. I checked my user client Windows notification settings and its set to showing all notifications and the focus assist is off. 

Am I missing something, cause the module's implementation seems pretty straight forward

**Comment by YuriyLisovskiy** [comment]
I need to check it up :)
I'll try to solve this issue soon.

**Comment by YuriyLisovskiy** [comment]
Oh, I've just seen you are using linux server. So, could you please check if this server supports desktop notifications?

**Comment by FinalSh4re** [comment]
You need the libnotify package to send notifications from the terminal.
I don't know what you are running, but at least on my Arch machine it's not installed by default. 
So you probably want to check for that.

@YuriyLisovskiy You might want to add it to the requirements.

**Comment by YuriyLisovskiy** [comment]
Yeah, I forgot to add it to the requirements. Thank you.
For using this library you need to install `libnotify-bin`.

**Comment by YuriyLisovskiy** [comment]
Closed because it seems the issue was resolved. Please, open it again if it will be needed.
