### ISSUE TITLE
Why did you chose 'description' to be an optional parameter?

### ISSUE THREAD

**Issue by antchal** [YuriyLisovskiy/pynotifier#4]
Wouldn't it be better if 'description' in initializer was an optional parameter?

PS:
I've tried it on my local system—making it optional doesn't break anything (at least on Linux).

**Comment by YuriyLisovskiy** [comment]
Yes, you are right, it is a good idea to make 'description' optional.
I'll do it soon.

**Comment by YuriyLisovskiy** [comment]
Done. I've already deployed the module to PyPi.

**Comment by antchal** [comment]
What about directly using 'low', 'normal', and 'critical' instead of through the defined constants? Wouldn't the code become more readable and succinct?
I don't think you will have scalability issues by getting away with these constants, will you?
